#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_postgresql | bash
#
# wget https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_postgresql -O install_postgresql
#
# Postgresql
#

set -e
set -x

# Condition check

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi

# Install 

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install -y postgresql-client postgresql

# Change config

echo "listen_addresses = '*'" >> /etc/postgresql/12/main/postgresql.conf
echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/12/main/pg_hba.conf

# Reboot

systemctl restart postgresql
systemctl status postgresql

