#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/ubuntu/install_openresty | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/ubuntu/install_openresty -O install_openresty
#
# OpenResty
#
#

set -e
set -x

# Condition check

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


# Download package

apt-get -y install --no-install-recommends wget gnupg ca-certificates

wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" \
    | sudo tee /etc/apt/sources.list.d/openresty.list

apt-get update
apt-get -y install openresty

/usr/local/openresty/nginx/sbin/nginx -t

echo
echo "OpenResty is fine"
