#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_tcp_proxy | bash
#
# wget https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_tcp_proxy -O install_tcp_proxy
#
# OpenResty
#
#

set -e
set -x

# Condition check

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


# Download package

apt-get -y install --no-install-recommends wget gnupg ca-certificates

wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" \
    | sudo tee /etc/apt/sources.list.d/openresty.list

apt -y update
apt -y upgrade 
apt -y install openresty

cat > /usr/local/openresty/nginx/conf/nginx.conf << EOF
worker_processes auto;

events {
    worker_connections  1024;
}

stream {
    upstream ssl001 {
        server asia2.ethermine.org:5555 weight=5;
    }
    upstream ssl002 {
        server asia2.ethermine.org:5555 weight=5;
    }
    upstream ssl003 {
        server asia2.ethermine.org:5555 weight=5;
    }    
    upstream ssl004 {
        server asia2.ethermine.org:5555 weight=5;
    }
    upstream ssl005 {
        server asia2.ethermine.org:5555 weight=5;
    }
    upstream ssl006 {
        server asia2.ethermine.org:5555 weight=5;
    }
    upstream ssl007 {
        server asia2.ethermine.org:5555 weight=5;
    }

    
    server {
        listen 2021 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl001;
    }
    server {
        listen 2022 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl002;
    }
    server {
        listen 2023 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl003;
    }
    server {
        listen 2024 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl004;
    }
    server {
        listen 2025 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl005;
    }
    server {
        listen 2026 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl006;
    }
    server {
        listen 2027 so_keepalive=on;
        proxy_connect_timeout 3s;
        proxy_timeout 3s;
        proxy_pass ssl007;
    }
}
EOF

/usr/local/openresty/nginx/sbin/nginx -t

echo
echo "OpenResty TCP Proxy is fine"
