#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/setup/unknown/install_google_authenticator | bash
#
# wget https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/setup/unknown/install_google_authenticator -O install_jq
#
# google-authenticator
#


set -e
set -x

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


OS=`curl https://raw.githubusercontent.com/WALL-E/static/master/utils/get_os_string 2>/dev/null | bash`

if [ "$OS" = "redhat" ]; then
    curl https://raw.githubusercontent.com/WALL-E/static/master/setup/redhat/install_google_authenticator | bash
fi

if [ "$OS" = "centos" ]; then
    curl https://raw.githubusercontent.com/WALL-E/static/master/setup/centos/install_google_authenticator | bash
fi

if [ "$OS" = "amazon" ]; then
    curl https://raw.githubusercontent.com/WALL-E/static/master/setup/amazon/install_google_authenticator | bash
fi

if [ "$OS" = "ubuntu" ]; then
    curl https://raw.githubusercontent.com/WALL-E/static/master/setup/ubuntu/install_google_authenticator | bash
fi

echo
echo "google-authenticator is fine"
