#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_tmux | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_tmux -O install_tmux
#
# tmux
#


set -e
set -x

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


OS=`curl https://raw.githubusercontent.com/WALL-E/static/master/utils/get_os_string 2>/dev/null | bash`

if [ "$OS" = "redhat" ]; then
    yum update -y
    yum upgrade -y
    
    yum install -y tmux
    wget -t 3 -O ~/.tmux.conf https://raw.githubusercontent.com/WALL-E/config/master/tmux/tmux.conf
fi

if [ "$OS" = "centos" ]; then
    yum update -y
    yum upgrade -y

    yum install -y tmux
    wget -t 3 -O ~/.tmux.conf https://raw.githubusercontent.com/WALL-E/config/master/tmux/tmux.conf
fi

if [ "$OS" = "amazon" ]; then
    yum update -y
    yum upgrade -y

    yum install -y tmux
    wget -t 3 -O ~/.tmux.conf https://raw.githubusercontent.com/WALL-E/config/master/tmux/tmux.conf
fi

if [ "$OS" = "ubuntu" ]; then
    apt update -y
    apt upgrade -y

    apt install -y tmux
    wget -t 3 -O ~/.tmux.conf https://raw.githubusercontent.com/WALL-E/config/master/tmux/tmux.conf
fi

echo
echo "tmux is fine"
