#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_pip3 | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_pip3 -O install_pip3
#
# pip
#

set -e
set -x

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


which pip3 || curl https://bootstrap.pypa.io/get-pip.py | python3

echo
echo "pip3 is fine"
