#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_inotify | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/install_inotify -O install_inotify
#
# inotify
#


set -e
set -x

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


OS=`curl https://raw.githubusercontent.com/WALL-E/static/master/utils/get_os_string 2>/dev/null | bash`

if [ "$OS" = "redhat" ]; then
    yum install -y inotify-tools
fi

if [ "$OS" = "centos" ]; then
    yum install -y inotify-tools
fi

if [ "$OS" = "amazon" ]; then
    yum install -y inotify-tools
fi

if [ "$OS" = "ubuntu" ]; then
    apt install -y inotify-tools
fi

echo
echo "inotify-tools is fine"
