#!/bin/bash

URL="http://172.28.32.102/jdk1.7.0_75.tgz"

role=`id -u`
if test $role -ne 0
then
    echo "You install JDK which requires root privileges"
    exit 1
fi

echo "start install jdk ..."

cd `dirname $0`
TMPFILE=$(mktemp /tmp/tmp.XXXXXXXXXX) || exit 1
wget -t 3 -O $TMPFILE $URL

tar zxf $TMPFILE -C /opt/

rm -f  $TMPFILE

cat <<EOF >> /etc/profile
JAVA_HOME=/opt/jdk1.7.0_75
JRE_HOME=\$JAVA_HOME/jre
PATH=\$PATH:\$JAVA_HOME/bin:\$JRE_HOME/bin
CLASSPATH=.:\$JRE_HOME/lib
export JAVA_HOME JRE_HOME PATH CLASSPATH
EOF

echo "you have to re-logo Or #source /etc/profile#"
