#!/usr/bin/env python3

#
# Python 3.6+ support
#

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_eth1_health | python3
#
# wget curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_eth1_health -O infura_eth1_health
#

#
# requires your to be set the environment variable before running
#
# Infura Project ID:
#
#     export WEB3_INFURA_PROJECT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#
# Ding Bot Access Token:
#
#     export DING_BOT_ACCESS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#


import requests

payload = {"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}
r = requests.post(infura_url, data=json.dumps(payload), headers=headers)
print(r.json())
