#!/usr/bin/env python3

#
# Python 3.6+ support
#

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_eth1_health | python3
#
# wget curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_eth1_health -O infura_eth1_health
#

#
# requires your to be set the environment variable before running
#
# Infura Project ID:
#
#     export WEB3_INFURA_PROJECT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#
# Ding Bot Access Token:
#
#     export DING_BOT_ACCESS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#

from web3.auto.infura import w3

if not w3.isConnected():
  # send msg to dingding
  print("[eth] [infura] geth is not available")
else:
  print("[eth] [infura] geth is available")
