#!/usr/bin/env python3

#
# Python 3.6+ support
#

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_health | python3
#
# wget curl https://raw.githubusercontent.com/WALL-E/static/master/eth/geth/infura_health -O infura_health
#

#
# requires your to be set the environment variable before running
#
# Infura Project ID:
#
#     export WEB3_INFURA_PROJECT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#
# Ding Bot Access Token:
#
#     export DING_BOT_ACCESS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#

import os
import requests

infura_project_id = os.getenv("WEB3_INFURA_PROJECT_ID")
infura_url = 'https://mainnet.infura.io/v3/' + infura_project_id
headers = {'Content-Type': 'application/json'}


payload = '{"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}'
r = requests.post(infura_url, data=payload, headers=headers)
print(r.json())
