#!/usr/bin/env python3


#
# Python 3.6+ support
#

#
# curl https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/eth/geth/own_health | python3
#
# wget curl https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/eth/geth/own_health -O own_health
#


#
# requires your to be set the environment variable before running
#
# Ding Bot Access Token:
#
#     export DING_BOT_ACCESS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#


import os
import requests

url = 'http://localhost:8545'
headers = {'Content-Type': 'application/json'}


payload = '{"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}'
r = requests.post(url, data=payload, headers=headers)
print(r.json())
