#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/amazon/install_google_authenticator | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/amazon/install_google_authenticator -O install_google_authenticator
#
# google-authenticator
#
#

set -e
set -x

# Condition check

role=`id -u`
if test $role -ne 0
then
    echo "You install package which requires root privileges"
    exit 1
fi


# Install google-authenticator

yum update -y
yum -y install autoconf automake libtool pam-devel git make

cd ~
git clone https://github.com/google/google-authenticator-libpam.git
cd google-authenticator-libpam
./bootstrap.sh
./configure
make
sudo make install
cp /usr/local/lib/security/pam_google_authenticator.so /usr/lib64/security/
cd -
rm -f google-authenticator-libpam


google-authenticator -h

echo
echo "google-authenticator is fine"
