#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "You init OS which requires root privileges"
exit 1
fi

yum update  -y yum
yum install -y yum-cron
yum install -y epel-release
yum install -y ntpdate
yum install -y git
yum install -y vim
yum install -y lsof
yum install -y wget
yum install -y net-tools
yum install -y tcpdump
yum install -y sysstat

ntpdate 133.100.11.8
grep "ntpdate" /var/spool/cron/root
ret=$?
if test $ret -ne 0
then
    echo "*/5 * * * * /usr/sbin/ntpdate 133.100.11.8" >> /var/spool/cron/root
fi

timedatectl set-timezone Asia/Shanghai
echo 'LANG="zh_CN.UTF-8"'  > /etc/locale.conf
localedef -v -c -i zh_CN -f UTF-8 zh_CN.UTF-8

systemctl stop firewalld.service && systemctl disable firewalld.service

