#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "运行脚本需要root权限"
    exit 1
fi

cd `dirname $0`

yum install -y epel-release
yum install -y python-virtualenv
yum install -y sqlite-devel sqlite
yum install -y gcc gcc-c++ automake
# yum groupinstall -y 'development tools'
yum install -y zlib-devel bzip2-devel openssl-devel xz-libs wget
yum install -y readline-devel readline patch unzip
yum install -y mariadb-server mariadb-devel mariadb

command -v python3.6
if test $? -ne 0
then
    wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
    xz -d Python-3.6.3.tar.xz
    tar xvf Python-3.6.3.tar
    cd Python-3.6.3
    ./configure --prefix=/usr/local --enable-shared
    make && make install && make libinstall
    cd -
    rm -fr Python-3.6.3
fi
# ln -s /usr/local/bin/python3.6 /usr/bin/python3.6

command -v easy_install-3.6
if test $? -ne 0
then
    wget https://pypi.python.org/packages/7c/cb/bdfbb0b6a56459d5461768de824d4f40ec4c4c778f3a8fb0b84c25f03b68/setuptools-37.0.0.zip#md5=f905ca70d2db37b7284c0f6314ab6814
    unzip setuptools-37.0.0.zip
    cd setuptools-37.0.0
    python3.6 setup.py install
    cd -
    rm -fr setuptools-37.0.0
fi

echo "/usr/local/lib" > /etc/ld.so.conf.d/python-3.6.conf
ldconfig

command -v pip3.6
if test $? -ne 0
then
    easy_install-3.6 pip
fi
