#!/bin/bash

curl https://raw.githubusercontent.com/WALL-E/static/master/setup/redhat/install_python36|bash

pip3.6 install http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp36-cp36m-linux_x86_64.whl 
pip3.6 install torchvision
pip3.6 install matplotlib
