#!/bin/bash


yum install -y wget xz

wget https://nodejs.org/dist/v8.9.1/node-v8.9.1-linux-x64.tar.xz

xz -d node-v8.9.1-linux-x64.tar.xz

tar xvf node-v8.9.1-linux-x64.tar


/bin/cp -rf node-v8.9.1-linux-x64 /usr/local/node

rm -fr node-v8.9.1-linux-x64 node-v8.9.1-linux-x64.tar

echo 'PATH=$PATH:/usr/local/node/bin/' >> ~/.bash_profile
echo 'export PATH' >> ~/.bash_profile

echo 'pls run: source ~/.bash_profile'
