#!/bin/bash

tmp_dir=/opt/harbor

role=`id -u`
if test $role -ne 0
then
    echo "You install Harbor which requires root privileges"
    exit 1
fi

(command -v docker || echo "please install docker";exit 1)
(command -v git || yum -y install git)
(command -v curl || yum -y install curl)

(systemctl status docker || systemctl start docker)

curl -L http://oerp142a4.bkt.clouddn.com/docker-compose-Linux-x86_64_1.8.0 > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

git clone https://github.com/vmware/harbor ${tmp_dir}

cd ${tmp_dir}/Deploy

ipaddr=`ip route get 202.106.0.20|grep "202.106.0.20"|awk '{print $7}'`
sed -i "s/^hostname.*$/hostname = ${ipaddr}/" harbor.cfg

./prepare

for i in {1..10}
do
   docker-compose up -d && break
done
