#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "You install JDK which requires root privileges"
    exit 1
fi

ssh-keygen -f /root/.ssh/id_rsa

cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
