#!/bin/bash

URL="http://oerp142a4.bkt.clouddn.com/apache-cassandra-2.2.7-bin.tar.gz"

role=`id -u`
if test $role -ne 0
then
    echo "You install Cassandra which requires root privileges"
    exit 1
fi

echo "start install cassandra ..."

cd `dirname $0`
TMPFILE=$(mktemp /tmp/tmp.XXXXXXXXXX) || exit 1
wget -t 3 -O $TMPFILE $URL

tar zxf $TMPFILE -C /opt/

rm -f  $TMPFILE

cat <<EOF >> /etc/profile
CASSANDRA_HOME=/opt/apache-cassandra-2.2.7
PATH=\$PATH:\$CASSANDRA_HOME/bin
export PATH
EOF

echo "you have to re-logo Or #source /etc/profile#"
