#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "运行脚本需要root权限"
    exit 1
fi

command -v pip2.7 > /dev/null 2>/dev/null
ret=$?
if test $role -ne 0
then
    echo "需要安装pip2.7"
    exit 1
fi

cd `dirname $0`

pip2.7 install http://oerp142a4.bkt.clouddn.com/supervisor-3.3.1.tar.gz

echo_supervisord_conf > /tmp/supervisord.conf
sudo cp /tmp/supervisord.conf /etc/
rm -f /tmp/supervisord.conf
