#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "运行脚本需要root权限"
    exit 1
fi

cd `dirname $0`

yum groupinstall -y 'development tools'
yum install -y zlib-devel bzip2-devel openssl-devel xz-libs wget


wget http://opduyrvvz.bkt.clouddn.com/Python-3.6.0.tgz
tar zxvf Python-3.6.0.tgz
cd Python-3.6.0
./configure --prefix=/usr/local --enable-shared
make && make install && make libinstall
cd -
rm -fr Python-3.6.0

ln -s /usr/local/bin/python3.6 /usr/bin/python3.6

wget http://opduyrvvz.bkt.clouddn.com/setuptools-36.0.1.zip
unzip setuptools-36.0.1.zip
cd setuptools-36.0.1
python3.6 setup.py install
cd -
rm -fr setuptools-36.0.1

easy_install-3.6 pip

ln -s /usr/local/bin/python3.6 /usr/bin/python3.6

echo "/usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu" > /etc/ld.so.conf.d/python-3.6.conf
ldconfig
