#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "Root permissions are required"
    exit 1
fi

cd ~
command -v kong
if test $? -ne 0
then
    sudo yum update -y
    sudo yum install -y wget
    wget https://bintray.com/kong/kong-rpm/rpm -O bintray-kong-kong-rpm.repo
    export major_version=`grep -oE '[0-9]+\.[0-9]+' /etc/redhat-release | cut -d "." -f1`
    sed -i -e 's/baseurl.*/&\/centos\/'$major_version''/ bintray-kong-kong-rpm.repo
    sudo mv bintray-kong-kong-rpm.repo /etc/yum.repos.d/
    sudo yum update -y
    sudo yum install -y kong
fi

command -v psql
if test $? -ne 0
then
    yum install -y https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.6-x86_64/pgdg-centos10-10-2.noarch.rpm
    yum install -y postgresql10
    yum install -y postgresql10-server


    /usr/pgsql-10/bin/postgresql-10-setup initdb
    systemctl enable postgresql-10
    systemctl start postgresql-10
fi

cd /tmp
sudo -u postgres createuser kong
sudo -u postgres createdb -O kong kong
sudo -u postgres createdb -O kong kong_tests
cd -

echo "change /var/lib/pgsql/10/data/pg_hba.conf, set 127.0.0.1/32 to trust"
echo "systemctl restart postgresql-10"
echo "postgre user: kong"
echo "postgre db: kong"
echo "change /etc/kong/kong.conf"
echo "kong migrations bootstrap"
echo "kong start"
