#!/bin/bash

set -x
set -e

role=`id -u`
if test $role -ne 0
then
    echo "Root permissions are required"
    exit 1
fi

command -v git
if test $? -ne 0
then
    yum install -y git
fi

wget http://oo2fuseka.bkt.clouddn.com/go1.8.3.linux-amd64.tar.gz
tar -C ${HOME} -xzf go1.8.3.linux-amd64.tar.gz

echo "export GOROOT=${HOME}/go" >> ~/.bashrc
echo "export GOPATH=${HOME}/work" >> ~/.bashrc
echo "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin" >> ~/.bashrc

source ~/.bashrc

go env
go version
