#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "运行脚本需要root权限"
    exit 1
fi

cd `dirname $0`

yum groupinstall -y 'development tools'
yum install -y zlib-devel bzip2-devel openssl-devel xz-libs wget


wget http://oerp142a4.bkt.clouddn.com/Python-2.7.13.tgz
tar zxvf Python-2.7.13.tgz
cd Python-2.7.13
./configure --prefix=/usr/local
make && make install
cd -
rm -fr Python-2.7.13

ln -s /usr/local/bin/python2.7 /usr/bin/python2.7

wget http://oerp142a4.bkt.clouddn.com/setuptools-32.3.1.zip
unzip setuptools-32.3.1.zip
cd setuptools-32.3.1
python2.7 setup.py install
cd -
rm -fr setuptools-32.3.1

wget http://oerp142a4.bkt.clouddn.com/pip-9.0.1.tar.gz
tar zxvf pip-9.0.1.tar.gz
cd pip-9.0.1
python2.7 setup.py install
cd -
rm -fr pip-9.0.1

ln -s /usr/local/bin/python2.7 /usr/bin/python2.7
ln -s /usr/local/bin/pip2.7 /usr/bin/pip2.7
