#!/bin/bash

role=`id -u`
if test $role -ne 0
then
    echo "运行脚本需要root权限"
    exit 1
fi

command -v unzip || yum -y install unzip || exit 1


command -v python2.7 > /dev/null 2>/dev/null
ret=$?
if test $role -ne 0
then
    echo "需要安装python2.7"
    exit 1
fi

cd `dirname $0`

wget http://oerp142a4.bkt.clouddn.com/setuptools-32.3.1.zip
unzip setuptools-32.3.1.zip
cd setuptools-32.3.1
python2.7 setup.py install
cd -
rm -fr setuptools-32.3.1
rm -f setuptools-32.3.1.zip

wget http://oerp142a4.bkt.clouddn.com/pip-9.0.1.tar.gz
tar zxvf pip-9.0.1.tar.gz
cd pip-9.0.1
python2.7 setup.py install
cd -
rm -fr pip-9.0.1
rm -f pip-9.0.1.tar.gz
