#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/chainlink/install_chainlink_rinkeby | bash
#
# wget https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/chainlink/install_chainlink_rinkeby -O install_chainlink_rinkeby
#
# Chainlink rinkeby
#
# ENV: 
#    export ETH_URL="wss://rinkeby.infura.io/ws/v3/XXXXXXXXXX"
#    export POSTGRESQL_HOST="10.168.0.2"
#

set -e
set -x


rm -fr ~/.chainlink-rinkeby
mkdir ~/.chainlink-rinkeby


echo "ROOT=/chainlink
LOG_LEVEL=debug
ETH_CHAIN_ID=4
CHAINLINK_TLS_PORT=0
SECURE_COOKIES=false
ALLOW_ORIGINS=*
ETH_URL=${ETH_URL}
DATABASE_URL=postgresql://chainlink:123456@${POSTGRESQL_HOST}:5432/chainlink
DATABASE_TIMEOUT=0" > ~/.chainlink-rinkeby/.env


echo "username@chainlink.com" > ~/.chainlink-rinkeby/.api
echo "AAAbbb@123456" >> ~/.chainlink-rinkeby/.api
echo "AAAbbb@123456" > ~/.chainlink-rinkeby/.password


echo "
cd ~/.chainlink-rinkeby
docker run --rm \
  -p 6688:6688 \
  -v ~/.chainlink-rinkeby:/chainlink \
  -itd \
  --env-file=.env \
  smartcontract/chainlink:1.1.1 local n \
  -p /chainlink/.password \
  -a /chainlink/.api
"
