#!/bin/bash
#
#
#

# PostgreSQL 

curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_postgresql | bash

curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/chainlink/init_postgresql | bash


# unknown

curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/setup/ubuntu/install_docker | bash

curl https://raw.githubusercontent.com/WALL-E/crypto-toolkit/master/chainlink/install_chainlink_rinkeby | bash
