#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/eth/lighthouse/health | bash
#
# wget https://raw.githubusercontent.com/WALL-E/eth-toolkit/master/eth/lighthouse/health -O health
#
# lighthouse beacon API
# 
# health
#

curl -X GET "http://localhost:5052/lighthouse/health" \
-H  "accept: application/json" | jq
