#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/syncing | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/syncing -O syncing
#
# lighthouse beacon API
# 
# syncing
#

curl -X GET "http://localhost:5052/lighthouse/syncing" \
-H  "accept: application/json" | jq
