#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/prometheus/install_prometheus | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/setup/unknown/prometheus/install_prometheus -O install_prometheus
#
# lighthouse beacon API
# 
# syncing
#

curl -X GET "http://localhost:5052/lighthouse/syncing" \
-H  "accept: application/json" | jq
