#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/version | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/version -O version
#
# lighthouse beacon API
# 
# version
#

set -e
set -x


echo "Lighthouse Beacon"
curl -X GET "http://localhost:5052/eth/v1/node/version" \
-H  "accept: application/json" 2>/dev/null | jq .

echo "Lighthouse Validator"
token=`cat /var/lib/lighthouse/validators/api-token.txt`
curl -X GET "http://localhost:5062/lighthouse/version" \
-H  "accept: application/json" \
-H  "Authorization: Basic $token" 2>/dev/null | jq .
