#!/bin/bash

#
# curl https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/version | bash
#
# wget https://raw.githubusercontent.com/WALL-E/static/master/eth/lighthouse/version -O version
#
# lighthouse beacon API
# 
# version
#

set -e
set -x


curl -X GET "http://localhost:5052/eth/v1/node/version" \
-H  "accept: application/json" | jq .

curl -X GET "http://localhost:5062/eth/v1/node/version" \
-H  "accept: application/json" | jq .
